spring:
  application:
    name: customers
  profiles:
    active: production
  datasource:
    url: ${customers.spring.datasource.url}
    username: ${customers.spring.datasource.username}
    password: ${customers.spring.datasource.password}
    jpa:
      database: ${customers.spring.jpa.database}
      show-sql: ${customers.spring.jpa.show-sql}
      hibernate:
        ddl-auto: ${customers.spring.jpa.hibernate.ddl-auto}
server:
  port: ${customers.server.port}

# ACTUATOR INFO
info:
  app:
    name: "Customers"
    version: "0.0.1"
    profile: ${spring.profiles.active}
  serverInfo:
    port: ${customers.server.port}

#actuator
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

application:
  allow-get-customers: ${customers.allow-get-customers}

eureka: #comment these two in case of ribbon
  client: ${eureka-client}
  instance:
      prefer-ip-address: true

feign:
  hystrix:
    enabled: true

#accounts:
#   ribbon:
#      eureka:
#         enabled: false
#
#      listOfServers: localhost:9999,localhost:9998
#
#cards:
#   ribbon:
#      eureka:
#         enabled: false
#
#      listOfServers: localhost:7050